== Benötige ich explizite Versionierung?

=== Was sind nicht rückwärtskompatible Änderungen?

[%step]
* Bei einer nichtrückärtskompatiblen Änderung wird der Konsument gezwungen etwas zu tun.


[NOTE.speaker]
--
* eine sehr strenge Definition
* was tun, kann Konfigurativ sein oder es muss eine neue Software gebaut released und deployed werden
* KÖNNEN, weil ich im Moment der Anpassung nicht weiss, ob der Teil den ich ändere tatsächlich von einem Konsumenten genutzt wird

--

=== Beispiele für nicht rückwärtskompatible Änderungen?
//
//[%step]
//* Verändern des Endpoints
//* Löschen von Attributen in Datenstrukturen
//* Umbennen von Attributen in Datenstrukturen
//* Attribute in Requests mandatory machen
//* Attribute in Response optional machen
//* Anpassungen an Enumwerten
//* Verändern von impliziten Annahmen
//
//[NOTE.speaker]
//--
//* KÖNNEN, weil ich im Moment der Anpassung nicht weiss, ob der Teil den ich ändere tatsächlich von einem //Konsumenten genutzt wird
//* Ändern des Endpoints (andere URI , anderer HOST)
//* Listen statt einzelner Werte
//* enums: weil wenn ich neue Werte schicke, kann ein Client darauf nicht reagieren und Fehler machen (z.B. 3. //Klasse)
//* implizite Annahmen
//** andere Repräsentation eines Strings: wenn ich einen String als Basis nehme um daraus etwas abzuleiten, oder //nach einem bestimmten Pattern parse, Beispiel z.B. "1. Klasse" statt "1. KLASSE"
//** Reihenfolgen von Sequencen, z.B. zuerst teuere, dann billige Angebote
//--

=== Verändern des Endpoints

.alt
[source]
----
htp://www.orange.ch/api/
----

.neu
[source]
----
htp://www.salt.ch/api
----

=== Löschen von Attributen in Datenstrukturen

.alt
[source, java]
----
public class Billett {
 private String klasse;
}
----

.neu
[source, java]
----
public class Billett {
}
----

=== Umbennen von Attributen in Datenstrukturen

.alt
[source, java]
----
public class Billett {
 private String klasse;
}
----

.neu
[source, java]
----
public class Billett {
 private String k_l_a_s_s_e;
}
----


=== Attribute in Requests mandatory machen

.alt
[source, xml]
----
 <xs:complexType name="RequestType">
    <xs:sequence>
        <xs:element name="name" type="string" minOccurs="0"/>
    </xs:sequence>
 </complexType>
----

.neu
[source, xml]
----
 <xs:complexType name="RequestType">
    <xs:sequence>
        <xs:element name="name" type="string" minOccurs="1"/>
    </xs:sequence>
 </complexType>
----


=== Attribute in Response optional machen

.alt
[source, xml]
----
 <xs:complexType name="RequestType">
    <xs:sequence>
        <xs:element name="name" type="string" minOccurs="1"/>
    </xs:sequence>
 </complexType>
----

.neu
[source, xml]
----
 <xs:complexType name="RequestType">
    <xs:sequence>
        <xs:element name="name" type="string" minOccurs="0"/>
    </xs:sequence>
 </complexType>
----


=== Anpassungen an Enumwerten

.alt
[source, java]
----
 public enum Klasse {
   Klasse_1,
   Klasse_2
 }

----

.neu
[source, java]
----
 public enum Klasse {
   Klasse_1,
   Klasse_3
 }
----

[NOTE.speaker]
--
enums: weil wenn ich neue Werte schicke, kann ein Client darauf nicht reagieren und Fehler machen (z.B. 3. //Klasse)
--


=== Verändern von impliziten Annahmen (Repräsentation)

.alt
[source]
----
 "1. Klasse"

----

.neu
[source]
----
 "1.KL"
----

[NOTE.speaker]
--
* andere Repräsentation eines Strings: wenn ich einen String als Basis nehme um daraus etwas abzuleiten, oder //nach einem bestimmten Pattern parse, Beispiel z.B. "1. Klasse" statt "1. KLASSE"
--

=== Verändern von impliziten Annahmen (Reihenfolge)

.alt
[source]
----
 [{Angebot1, 200 CHF},
  {Angebot2, 100 CHF}]
----

.neu
[source]
----
 [{Angebot2, 100 CHF},
  {Angebot1, 200 CHF}]
----

[NOTE.speaker]
--
** Reihenfolgen von Sequencen, z.B. zuerst teuere, dann billige Angebote
--

=== Verändern Parameterreihenfolge in Operationen

.alt
[source, java]
----
 public ResponseType foo(String name, Date birthdate);
----

.neu
[source, java]
----
 public ResponseType foo(Date birthdate, String name);
----

=== Entfernen umbennen von Operationen


.alt
[source, java]
----
 interface Service {
    ResponseFoo foo(RequestFoo request);
    ResponseBar foo(RequestBar request);
 }
----

.neu
[source, java]
----
 interface Service {
     ResponseFoo fooFoo(RequestFoo request);
  }
----


=== Was spricht für explizite Serviceversionierung?

[%step]
* Hauptgrund: Entkopplung zwischen Service und Konsument
* Nicht rückwärtskompatible Änderung ist unvermeidbar
* Lebenszyklus Konsument und Service ungleich
* Verträge mit Konsumenten
* Nicht alle Konsumenten bekannt

[NOTE.speaker]
--
* nicht vermeidbar: Abbau von Altlasten, Vereinfachungen, entfernen von Redundanzen
* Konsumenten:
** Integration eines Servies kann aufwendig sein mit
** Verträgen können das Risiko reduziert werden, dass Konsument häufig integrieren muss
** Verträge regeln, wie lange eine Version verfügbar sein muss (z.B. Schnittstelle SNCF: alle halbe Jahre migration notwendig)
*  Unterschiedliche Lifecycle
** Konsument und Service können nicht gleichzeitg aktualisiert werden
** Beispiel Backendsysteme vom neuen Vertriebssystem und die vNext
** Alte Version müssen unterstützt werden, weil Wechsel zu einem beliebigen Zeitpunkt erfolgen kann
* Es sind nicht alle Konsumenten bekannt
** Wenn nicht alle Konsumenten bekannt sind, können unterschiedliche Schnittstellenversionen von alten Konsumenten noch im Einsatz sein
** Ich weiss nicht, ob ich immer alle erreichen kann
--

=== Was spricht gegen explizite Serviceversionierung?

[%step]
* Hauptgrund: Erhöht die Komplexität
* Schnittstellenänderungen immer rückwärtskompatibel
* Lebenszyklus Konsumenten und Service ist gleich
* Ressourcenmangel
* Konsumenten vom Service abhängig

[NOTE.speaker]
--
* Abhängig
** wenn ein Abhängigkeitsverhältnis von Konsumenten zum Service besteht, kann ich das nutzen und nur eine Version anbietem
** nicht sehr nett
* lebenszyklus gleich
** gleicher Lebenszyklus, es gehen beide gleichzeitig in Produktion
** in unteren Umgebungen Test ist es OK, wenn der Service eine definierte Zeit nicht angebunden ist
* Resourcenmangel
** Es fehlen die Ressourcen, um zwei Versionen eines Services zur Verfügung zu stellen
* rückwärtrskompatibel
** Wenn Änderungen immer rückwärtskompatibel durchgeführt werden können, dann ist es nicht nötig mehrere Versionen zu haben
** Beispiel ein sehr einfacher Service
* generell machen rückwaärtskopatible Serviceschnittststellen die Entwicklungs langsamer und führen zu einem verzögerten Rückbau von Features
--

=== Unsere Entscheidung

[%step]
* Explizite Versionierung unsere Serviceschnittstellen, weil
* Mobile & Automaten anderen Lebenszyklus haben
* Parallele Deployen von Services zu kostspielig ist

=== ... aber

[%step]
* Wir haben nicht alle Serviceschnittstellen versioniert
* Versionierung nur auf Aussen-Services
* Versionierung nur auf Teamübergreifenden Services
* Keine Versionierung auf Teaminternen Services

